name: Employee Management CI Pipeline

on:
  push:
    branches:
        - main
        - 'GHA-*'
    # paths:
    #     - "backend/**"
jobs:
    backend-build:
        runs-on: ubuntu-latest       
        steps:
            - name: Print Hello
              run: echo "Hello"

            - name: Checkout the code
              uses: actions/checkout@v4 

            - name: check the files
              run: ls   

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 22

            - name: Install Dependencies for the backend.
              working-directory: backend # Updated working directory
              run: npm ci

            - name: Install Frontend Dependencies
              working-directory: frontend
              run: npm ci

            - name: Build Frontend
              working-directory: frontend
              env:
                CI: false
              run: npm run build

            - name: Upload Frontend artifact
              uses: actions/upload-artifact@v7
              with:
                name: frontend-artifact
                path: frontend/build