name: Employee Management CI Pipeline

on:
  push:
    branches:
        - main
        - 'GHA-*'
    paths:
        - "backend/**"
jobs:
    backend-build:
        runs-on: ubuntu-latest       
        steps:
            - name: Print Hello
              run: echo "Hello"
            - name: Checkout the code
              uses: actions/checkout@4 
            - name: check the files
              run: ls   