name: CI Yaml
on:
    push:
      branches:
        - main    # This is the filtering of the branches and selecting main branch ONLY
        - 'dev-*'
        - 'feat-*'
      paths:
        - first-workflow.yml
      # paths-ignore:
      #   - .gitignore         
    pull_request:
      types: opened  #Event types
    workflow_dispatch: 

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Starting the pipeline
              run: echo "Hi"  
            
            - name: Checking out the code
              uses: actions/checkout@v7
              
            - name: Setup Node Action
              uses: actions/setup-node@v6
              with:
                node-verison: 24
                
            - name: Install Dependencies
              run: npm ci
